/*
 * Sources
 *
 * Sources
 *
 * API version: 3.1.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// BulkCreatePayloadSources struct for BulkCreatePayloadSources
type BulkCreatePayloadSources struct {
	Name *string `json:"name,omitempty"`
	// Source Type from supported types
	SourceTypeName *string `json:"source_type_name,omitempty"`
	SourceRef *string `json:"source_ref,omitempty"`
	SourceTypeId *string `json:"source_type_id,omitempty"`
}

// NewBulkCreatePayloadSources instantiates a new BulkCreatePayloadSources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreatePayloadSources() *BulkCreatePayloadSources {
	this := BulkCreatePayloadSources{}
	return &this
}

// NewBulkCreatePayloadSourcesWithDefaults instantiates a new BulkCreatePayloadSources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreatePayloadSourcesWithDefaults() *BulkCreatePayloadSources {
	this := BulkCreatePayloadSources{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BulkCreatePayloadSources) SetName(v string) {
	o.Name = &v
}

// GetSourceTypeName returns the SourceTypeName field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetSourceTypeName() string {
	if o == nil || o.SourceTypeName == nil {
		var ret string
		return ret
	}
	return *o.SourceTypeName
}

// GetSourceTypeNameOk returns a tuple with the SourceTypeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetSourceTypeNameOk() (*string, bool) {
	if o == nil || o.SourceTypeName == nil {
		return nil, false
	}
	return o.SourceTypeName, true
}

// HasSourceTypeName returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasSourceTypeName() bool {
	if o != nil && o.SourceTypeName != nil {
		return true
	}

	return false
}

// SetSourceTypeName gets a reference to the given string and assigns it to the SourceTypeName field.
func (o *BulkCreatePayloadSources) SetSourceTypeName(v string) {
	o.SourceTypeName = &v
}

// GetSourceRef returns the SourceRef field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetSourceRef() string {
	if o == nil || o.SourceRef == nil {
		var ret string
		return ret
	}
	return *o.SourceRef
}

// GetSourceRefOk returns a tuple with the SourceRef field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetSourceRefOk() (*string, bool) {
	if o == nil || o.SourceRef == nil {
		return nil, false
	}
	return o.SourceRef, true
}

// HasSourceRef returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasSourceRef() bool {
	if o != nil && o.SourceRef != nil {
		return true
	}

	return false
}

// SetSourceRef gets a reference to the given string and assigns it to the SourceRef field.
func (o *BulkCreatePayloadSources) SetSourceRef(v string) {
	o.SourceRef = &v
}

// GetSourceTypeId returns the SourceTypeId field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetSourceTypeId() string {
	if o == nil || o.SourceTypeId == nil {
		var ret string
		return ret
	}
	return *o.SourceTypeId
}

// GetSourceTypeIdOk returns a tuple with the SourceTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetSourceTypeIdOk() (*string, bool) {
	if o == nil || o.SourceTypeId == nil {
		return nil, false
	}
	return o.SourceTypeId, true
}

// HasSourceTypeId returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasSourceTypeId() bool {
	if o != nil && o.SourceTypeId != nil {
		return true
	}

	return false
}

// SetSourceTypeId gets a reference to the given string and assigns it to the SourceTypeId field.
func (o *BulkCreatePayloadSources) SetSourceTypeId(v string) {
	o.SourceTypeId = &v
}

func (o BulkCreatePayloadSources) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.SourceTypeName != nil {
		toSerialize["source_type_name"] = o.SourceTypeName
	}
	if o.SourceRef != nil {
		toSerialize["source_ref"] = o.SourceRef
	}
	if o.SourceTypeId != nil {
		toSerialize["source_type_id"] = o.SourceTypeId
	}
	return json.Marshal(toSerialize)
}

type NullableBulkCreatePayloadSources struct {
	value *BulkCreatePayloadSources
	isSet bool
}

func (v NullableBulkCreatePayloadSources) Get() *BulkCreatePayloadSources {
	return v.value
}

func (v *NullableBulkCreatePayloadSources) Set(val *BulkCreatePayloadSources) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreatePayloadSources) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreatePayloadSources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreatePayloadSources(val *BulkCreatePayloadSources) *NullableBulkCreatePayloadSources {
	return &NullableBulkCreatePayloadSources{value: val, isSet: true}
}

func (v NullableBulkCreatePayloadSources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreatePayloadSources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


