/*
 * Sources
 *
 * Sources
 *
 * API version: 3.0.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// GraphQLResponse struct for GraphQLResponse
type GraphQLResponse struct {
	// Results from the GraphQL query
	Data *map[string]interface{} `json:"data,omitempty"`
	// Errors resulting from the GraphQL query
	Errors *[]map[string]interface{} `json:"errors,omitempty"`
}

// NewGraphQLResponse instantiates a new GraphQLResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGraphQLResponse() *GraphQLResponse {
	this := GraphQLResponse{}
	return &this
}

// NewGraphQLResponseWithDefaults instantiates a new GraphQLResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGraphQLResponseWithDefaults() *GraphQLResponse {
	this := GraphQLResponse{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GraphQLResponse) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphQLResponse) GetDataOk() (*map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GraphQLResponse) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *GraphQLResponse) SetData(v map[string]interface{}) {
	o.Data = &v
}

// GetErrors returns the Errors field value if set, zero value otherwise.
func (o *GraphQLResponse) GetErrors() []map[string]interface{} {
	if o == nil || o.Errors == nil {
		var ret []map[string]interface{}
		return ret
	}
	return *o.Errors
}

// GetErrorsOk returns a tuple with the Errors field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GraphQLResponse) GetErrorsOk() (*[]map[string]interface{}, bool) {
	if o == nil || o.Errors == nil {
		return nil, false
	}
	return o.Errors, true
}

// HasErrors returns a boolean if a field has been set.
func (o *GraphQLResponse) HasErrors() bool {
	if o != nil && o.Errors != nil {
		return true
	}

	return false
}

// SetErrors gets a reference to the given []map[string]interface{} and assigns it to the Errors field.
func (o *GraphQLResponse) SetErrors(v []map[string]interface{}) {
	o.Errors = &v
}

func (o GraphQLResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	if o.Errors != nil {
		toSerialize["errors"] = o.Errors
	}
	return json.Marshal(toSerialize)
}

type NullableGraphQLResponse struct {
	value *GraphQLResponse
	isSet bool
}

func (v NullableGraphQLResponse) Get() *GraphQLResponse {
	return v.value
}

func (v *NullableGraphQLResponse) Set(val *GraphQLResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGraphQLResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGraphQLResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGraphQLResponse(val *GraphQLResponse) *NullableGraphQLResponse {
	return &NullableGraphQLResponse{value: val, isSet: true}
}

func (v NullableGraphQLResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGraphQLResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


