/*
 * Sources
 *
 * Sources
 *
 * API version: 3.1.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// BulkCreatePayloadEndpoints struct for BulkCreatePayloadEndpoints
type BulkCreatePayloadEndpoints struct {
	Scheme *string `json:"scheme,omitempty"`
	Host *string `json:"host,omitempty"`
	Path *string `json:"path,omitempty"`
	Port *int32 `json:"port,omitempty"`
	VerifySsl *bool `json:"verify_ssl,omitempty"`
	SourceName *string `json:"source_name,omitempty"`
}

// NewBulkCreatePayloadEndpoints instantiates a new BulkCreatePayloadEndpoints object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreatePayloadEndpoints() *BulkCreatePayloadEndpoints {
	this := BulkCreatePayloadEndpoints{}
	return &this
}

// NewBulkCreatePayloadEndpointsWithDefaults instantiates a new BulkCreatePayloadEndpoints object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreatePayloadEndpointsWithDefaults() *BulkCreatePayloadEndpoints {
	this := BulkCreatePayloadEndpoints{}
	return &this
}

// GetScheme returns the Scheme field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetScheme() string {
	if o == nil || o.Scheme == nil {
		var ret string
		return ret
	}
	return *o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetSchemeOk() (*string, bool) {
	if o == nil || o.Scheme == nil {
		return nil, false
	}
	return o.Scheme, true
}

// HasScheme returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasScheme() bool {
	if o != nil && o.Scheme != nil {
		return true
	}

	return false
}

// SetScheme gets a reference to the given string and assigns it to the Scheme field.
func (o *BulkCreatePayloadEndpoints) SetScheme(v string) {
	o.Scheme = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetHost() string {
	if o == nil || o.Host == nil {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetHostOk() (*string, bool) {
	if o == nil || o.Host == nil {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasHost() bool {
	if o != nil && o.Host != nil {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *BulkCreatePayloadEndpoints) SetHost(v string) {
	o.Host = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *BulkCreatePayloadEndpoints) SetPath(v string) {
	o.Path = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetPort() int32 {
	if o == nil || o.Port == nil {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetPortOk() (*int32, bool) {
	if o == nil || o.Port == nil {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasPort() bool {
	if o != nil && o.Port != nil {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *BulkCreatePayloadEndpoints) SetPort(v int32) {
	o.Port = &v
}

// GetVerifySsl returns the VerifySsl field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetVerifySsl() bool {
	if o == nil || o.VerifySsl == nil {
		var ret bool
		return ret
	}
	return *o.VerifySsl
}

// GetVerifySslOk returns a tuple with the VerifySsl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetVerifySslOk() (*bool, bool) {
	if o == nil || o.VerifySsl == nil {
		return nil, false
	}
	return o.VerifySsl, true
}

// HasVerifySsl returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasVerifySsl() bool {
	if o != nil && o.VerifySsl != nil {
		return true
	}

	return false
}

// SetVerifySsl gets a reference to the given bool and assigns it to the VerifySsl field.
func (o *BulkCreatePayloadEndpoints) SetVerifySsl(v bool) {
	o.VerifySsl = &v
}

// GetSourceName returns the SourceName field value if set, zero value otherwise.
func (o *BulkCreatePayloadEndpoints) GetSourceName() string {
	if o == nil || o.SourceName == nil {
		var ret string
		return ret
	}
	return *o.SourceName
}

// GetSourceNameOk returns a tuple with the SourceName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadEndpoints) GetSourceNameOk() (*string, bool) {
	if o == nil || o.SourceName == nil {
		return nil, false
	}
	return o.SourceName, true
}

// HasSourceName returns a boolean if a field has been set.
func (o *BulkCreatePayloadEndpoints) HasSourceName() bool {
	if o != nil && o.SourceName != nil {
		return true
	}

	return false
}

// SetSourceName gets a reference to the given string and assigns it to the SourceName field.
func (o *BulkCreatePayloadEndpoints) SetSourceName(v string) {
	o.SourceName = &v
}

func (o BulkCreatePayloadEndpoints) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Scheme != nil {
		toSerialize["scheme"] = o.Scheme
	}
	if o.Host != nil {
		toSerialize["host"] = o.Host
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Port != nil {
		toSerialize["port"] = o.Port
	}
	if o.VerifySsl != nil {
		toSerialize["verify_ssl"] = o.VerifySsl
	}
	if o.SourceName != nil {
		toSerialize["source_name"] = o.SourceName
	}
	return json.Marshal(toSerialize)
}

type NullableBulkCreatePayloadEndpoints struct {
	value *BulkCreatePayloadEndpoints
	isSet bool
}

func (v NullableBulkCreatePayloadEndpoints) Get() *BulkCreatePayloadEndpoints {
	return v.value
}

func (v *NullableBulkCreatePayloadEndpoints) Set(val *BulkCreatePayloadEndpoints) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreatePayloadEndpoints) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreatePayloadEndpoints) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreatePayloadEndpoints(val *BulkCreatePayloadEndpoints) *NullableBulkCreatePayloadEndpoints {
	return &NullableBulkCreatePayloadEndpoints{value: val, isSet: true}
}

func (v NullableBulkCreatePayloadEndpoints) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreatePayloadEndpoints) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


