/*
 * Sources
 *
 * Sources
 *
 * API version: 3.1.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// BulkCreatePayload struct for BulkCreatePayload
type BulkCreatePayload struct {
	SuperkeyRequest *SuperKeyRequest `json:"superkey_request,omitempty"`
	// Array of Source objects to create. Only supported fields are name + type, source_type_id will automatically be set based on the name. 
	Sources *[]BulkCreatePayloadSources `json:"sources,omitempty"`
	// Array of Endpoint objects to create. The operation looks up the parent source by the `source_name` attribute so the `source_name` must match one of the `source`'s names in the payload. 
	Endpoints *[]BulkCreatePayloadEndpoints `json:"endpoints,omitempty"`
	// Array of Application objects to create. The operation looks up the parent Source by the `source_name` attribute so the `source_name` must match one of the `source`'s names in the payload.  application_type_id will be automatically looked up and set by the `type` attribute via regex. 
	Applications *[]BulkCreatePayloadApplications `json:"applications,omitempty"`
	// Array of Authentications to create. This one is a bit more tricky. `resource_type` tells the action where to look for the parent, must be either application/endpoint/source  if the parent is a source, it looks up by name. if the parent is an endpoint, it looks up via host so the hostname must match. if the parent is an application, it looks up via application type so the value must match the application type which matches 
	Authentications *[]BulkCreatePayloadAuthentications `json:"authentications,omitempty"`
}

// NewBulkCreatePayload instantiates a new BulkCreatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreatePayload() *BulkCreatePayload {
	this := BulkCreatePayload{}
	return &this
}

// NewBulkCreatePayloadWithDefaults instantiates a new BulkCreatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreatePayloadWithDefaults() *BulkCreatePayload {
	this := BulkCreatePayload{}
	return &this
}

// GetSuperkeyRequest returns the SuperkeyRequest field value if set, zero value otherwise.
func (o *BulkCreatePayload) GetSuperkeyRequest() SuperKeyRequest {
	if o == nil || o.SuperkeyRequest == nil {
		var ret SuperKeyRequest
		return ret
	}
	return *o.SuperkeyRequest
}

// GetSuperkeyRequestOk returns a tuple with the SuperkeyRequest field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayload) GetSuperkeyRequestOk() (*SuperKeyRequest, bool) {
	if o == nil || o.SuperkeyRequest == nil {
		return nil, false
	}
	return o.SuperkeyRequest, true
}

// HasSuperkeyRequest returns a boolean if a field has been set.
func (o *BulkCreatePayload) HasSuperkeyRequest() bool {
	if o != nil && o.SuperkeyRequest != nil {
		return true
	}

	return false
}

// SetSuperkeyRequest gets a reference to the given SuperKeyRequest and assigns it to the SuperkeyRequest field.
func (o *BulkCreatePayload) SetSuperkeyRequest(v SuperKeyRequest) {
	o.SuperkeyRequest = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *BulkCreatePayload) GetSources() []BulkCreatePayloadSources {
	if o == nil || o.Sources == nil {
		var ret []BulkCreatePayloadSources
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayload) GetSourcesOk() (*[]BulkCreatePayloadSources, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *BulkCreatePayload) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []BulkCreatePayloadSources and assigns it to the Sources field.
func (o *BulkCreatePayload) SetSources(v []BulkCreatePayloadSources) {
	o.Sources = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *BulkCreatePayload) GetEndpoints() []BulkCreatePayloadEndpoints {
	if o == nil || o.Endpoints == nil {
		var ret []BulkCreatePayloadEndpoints
		return ret
	}
	return *o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayload) GetEndpointsOk() (*[]BulkCreatePayloadEndpoints, bool) {
	if o == nil || o.Endpoints == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *BulkCreatePayload) HasEndpoints() bool {
	if o != nil && o.Endpoints != nil {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []BulkCreatePayloadEndpoints and assigns it to the Endpoints field.
func (o *BulkCreatePayload) SetEndpoints(v []BulkCreatePayloadEndpoints) {
	o.Endpoints = &v
}

// GetApplications returns the Applications field value if set, zero value otherwise.
func (o *BulkCreatePayload) GetApplications() []BulkCreatePayloadApplications {
	if o == nil || o.Applications == nil {
		var ret []BulkCreatePayloadApplications
		return ret
	}
	return *o.Applications
}

// GetApplicationsOk returns a tuple with the Applications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayload) GetApplicationsOk() (*[]BulkCreatePayloadApplications, bool) {
	if o == nil || o.Applications == nil {
		return nil, false
	}
	return o.Applications, true
}

// HasApplications returns a boolean if a field has been set.
func (o *BulkCreatePayload) HasApplications() bool {
	if o != nil && o.Applications != nil {
		return true
	}

	return false
}

// SetApplications gets a reference to the given []BulkCreatePayloadApplications and assigns it to the Applications field.
func (o *BulkCreatePayload) SetApplications(v []BulkCreatePayloadApplications) {
	o.Applications = &v
}

// GetAuthentications returns the Authentications field value if set, zero value otherwise.
func (o *BulkCreatePayload) GetAuthentications() []BulkCreatePayloadAuthentications {
	if o == nil || o.Authentications == nil {
		var ret []BulkCreatePayloadAuthentications
		return ret
	}
	return *o.Authentications
}

// GetAuthenticationsOk returns a tuple with the Authentications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayload) GetAuthenticationsOk() (*[]BulkCreatePayloadAuthentications, bool) {
	if o == nil || o.Authentications == nil {
		return nil, false
	}
	return o.Authentications, true
}

// HasAuthentications returns a boolean if a field has been set.
func (o *BulkCreatePayload) HasAuthentications() bool {
	if o != nil && o.Authentications != nil {
		return true
	}

	return false
}

// SetAuthentications gets a reference to the given []BulkCreatePayloadAuthentications and assigns it to the Authentications field.
func (o *BulkCreatePayload) SetAuthentications(v []BulkCreatePayloadAuthentications) {
	o.Authentications = &v
}

func (o BulkCreatePayload) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SuperkeyRequest != nil {
		toSerialize["superkey_request"] = o.SuperkeyRequest
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	if o.Endpoints != nil {
		toSerialize["endpoints"] = o.Endpoints
	}
	if o.Applications != nil {
		toSerialize["applications"] = o.Applications
	}
	if o.Authentications != nil {
		toSerialize["authentications"] = o.Authentications
	}
	return json.Marshal(toSerialize)
}

type NullableBulkCreatePayload struct {
	value *BulkCreatePayload
	isSet bool
}

func (v NullableBulkCreatePayload) Get() *BulkCreatePayload {
	return v.value
}

func (v *NullableBulkCreatePayload) Set(val *BulkCreatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreatePayload(val *BulkCreatePayload) *NullableBulkCreatePayload {
	return &NullableBulkCreatePayload{value: val, isSet: true}
}

func (v NullableBulkCreatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


