/*
 * Sources
 *
 * Sources
 *
 * API version: 3.1.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// BulkCreateResponse struct for BulkCreateResponse
type BulkCreateResponse struct {
	Superkey *bool `json:"superkey,omitempty"`
	Sources *[]Source `json:"sources,omitempty"`
	Endpoints *[]Endpoint `json:"endpoints,omitempty"`
	Applications *[]Application `json:"applications,omitempty"`
	Authentications *[]Authentication `json:"authentications,omitempty"`
}

// NewBulkCreateResponse instantiates a new BulkCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreateResponse() *BulkCreateResponse {
	this := BulkCreateResponse{}
	var superkey bool = false
	this.Superkey = &superkey
	return &this
}

// NewBulkCreateResponseWithDefaults instantiates a new BulkCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreateResponseWithDefaults() *BulkCreateResponse {
	this := BulkCreateResponse{}
	var superkey bool = false
	this.Superkey = &superkey
	return &this
}

// GetSuperkey returns the Superkey field value if set, zero value otherwise.
func (o *BulkCreateResponse) GetSuperkey() bool {
	if o == nil || o.Superkey == nil {
		var ret bool
		return ret
	}
	return *o.Superkey
}

// GetSuperkeyOk returns a tuple with the Superkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateResponse) GetSuperkeyOk() (*bool, bool) {
	if o == nil || o.Superkey == nil {
		return nil, false
	}
	return o.Superkey, true
}

// HasSuperkey returns a boolean if a field has been set.
func (o *BulkCreateResponse) HasSuperkey() bool {
	if o != nil && o.Superkey != nil {
		return true
	}

	return false
}

// SetSuperkey gets a reference to the given bool and assigns it to the Superkey field.
func (o *BulkCreateResponse) SetSuperkey(v bool) {
	o.Superkey = &v
}

// GetSources returns the Sources field value if set, zero value otherwise.
func (o *BulkCreateResponse) GetSources() []Source {
	if o == nil || o.Sources == nil {
		var ret []Source
		return ret
	}
	return *o.Sources
}

// GetSourcesOk returns a tuple with the Sources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateResponse) GetSourcesOk() (*[]Source, bool) {
	if o == nil || o.Sources == nil {
		return nil, false
	}
	return o.Sources, true
}

// HasSources returns a boolean if a field has been set.
func (o *BulkCreateResponse) HasSources() bool {
	if o != nil && o.Sources != nil {
		return true
	}

	return false
}

// SetSources gets a reference to the given []Source and assigns it to the Sources field.
func (o *BulkCreateResponse) SetSources(v []Source) {
	o.Sources = &v
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *BulkCreateResponse) GetEndpoints() []Endpoint {
	if o == nil || o.Endpoints == nil {
		var ret []Endpoint
		return ret
	}
	return *o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateResponse) GetEndpointsOk() (*[]Endpoint, bool) {
	if o == nil || o.Endpoints == nil {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *BulkCreateResponse) HasEndpoints() bool {
	if o != nil && o.Endpoints != nil {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []Endpoint and assigns it to the Endpoints field.
func (o *BulkCreateResponse) SetEndpoints(v []Endpoint) {
	o.Endpoints = &v
}

// GetApplications returns the Applications field value if set, zero value otherwise.
func (o *BulkCreateResponse) GetApplications() []Application {
	if o == nil || o.Applications == nil {
		var ret []Application
		return ret
	}
	return *o.Applications
}

// GetApplicationsOk returns a tuple with the Applications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateResponse) GetApplicationsOk() (*[]Application, bool) {
	if o == nil || o.Applications == nil {
		return nil, false
	}
	return o.Applications, true
}

// HasApplications returns a boolean if a field has been set.
func (o *BulkCreateResponse) HasApplications() bool {
	if o != nil && o.Applications != nil {
		return true
	}

	return false
}

// SetApplications gets a reference to the given []Application and assigns it to the Applications field.
func (o *BulkCreateResponse) SetApplications(v []Application) {
	o.Applications = &v
}

// GetAuthentications returns the Authentications field value if set, zero value otherwise.
func (o *BulkCreateResponse) GetAuthentications() []Authentication {
	if o == nil || o.Authentications == nil {
		var ret []Authentication
		return ret
	}
	return *o.Authentications
}

// GetAuthenticationsOk returns a tuple with the Authentications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreateResponse) GetAuthenticationsOk() (*[]Authentication, bool) {
	if o == nil || o.Authentications == nil {
		return nil, false
	}
	return o.Authentications, true
}

// HasAuthentications returns a boolean if a field has been set.
func (o *BulkCreateResponse) HasAuthentications() bool {
	if o != nil && o.Authentications != nil {
		return true
	}

	return false
}

// SetAuthentications gets a reference to the given []Authentication and assigns it to the Authentications field.
func (o *BulkCreateResponse) SetAuthentications(v []Authentication) {
	o.Authentications = &v
}

func (o BulkCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Superkey != nil {
		toSerialize["superkey"] = o.Superkey
	}
	if o.Sources != nil {
		toSerialize["sources"] = o.Sources
	}
	if o.Endpoints != nil {
		toSerialize["endpoints"] = o.Endpoints
	}
	if o.Applications != nil {
		toSerialize["applications"] = o.Applications
	}
	if o.Authentications != nil {
		toSerialize["authentications"] = o.Authentications
	}
	return json.Marshal(toSerialize)
}

type NullableBulkCreateResponse struct {
	value *BulkCreateResponse
	isSet bool
}

func (v NullableBulkCreateResponse) Get() *BulkCreateResponse {
	return v.value
}

func (v *NullableBulkCreateResponse) Set(val *BulkCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreateResponse(val *BulkCreateResponse) *NullableBulkCreateResponse {
	return &NullableBulkCreateResponse{value: val, isSet: true}
}

func (v NullableBulkCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


