/*
 * Sources
 *
 * Sources
 *
 * API version: 3.1.0
 * Contact: support@redhat.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sourcesapi

import (
	"encoding/json"
)

// BulkCreatePayloadSources struct for BulkCreatePayloadSources
type BulkCreatePayloadSources struct {
	Name *string `json:"name,omitempty"`
	// Source Type from supported types
	Type *string `json:"type,omitempty"`
}

// NewBulkCreatePayloadSources instantiates a new BulkCreatePayloadSources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkCreatePayloadSources() *BulkCreatePayloadSources {
	this := BulkCreatePayloadSources{}
	return &this
}

// NewBulkCreatePayloadSourcesWithDefaults instantiates a new BulkCreatePayloadSources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkCreatePayloadSourcesWithDefaults() *BulkCreatePayloadSources {
	this := BulkCreatePayloadSources{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *BulkCreatePayloadSources) SetName(v string) {
	o.Name = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *BulkCreatePayloadSources) GetType() string {
	if o == nil || o.Type == nil {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkCreatePayloadSources) GetTypeOk() (*string, bool) {
	if o == nil || o.Type == nil {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *BulkCreatePayloadSources) HasType() bool {
	if o != nil && o.Type != nil {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *BulkCreatePayloadSources) SetType(v string) {
	o.Type = &v
}

func (o BulkCreatePayloadSources) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Type != nil {
		toSerialize["type"] = o.Type
	}
	return json.Marshal(toSerialize)
}

type NullableBulkCreatePayloadSources struct {
	value *BulkCreatePayloadSources
	isSet bool
}

func (v NullableBulkCreatePayloadSources) Get() *BulkCreatePayloadSources {
	return v.value
}

func (v *NullableBulkCreatePayloadSources) Set(val *BulkCreatePayloadSources) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkCreatePayloadSources) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkCreatePayloadSources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkCreatePayloadSources(val *BulkCreatePayloadSources) *NullableBulkCreatePayloadSources {
	return &NullableBulkCreatePayloadSources{value: val, isSet: true}
}

func (v NullableBulkCreatePayloadSources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkCreatePayloadSources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


